version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: items
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: