version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: items
    volumes:
      - db-data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./db/changelog:/liquibase/changelog
    depends_on:
      - db
    command:
      - --url=jdbc:postgresql://db:5432/postgres
      - --changeLogFile=/liquibase/changelog/db.changelog-master.xml
      - --username=postgres
      - --password=${POSTGRES_PASSWORD}
      - update

  item-service:
    image: item_service
    ports:
      - 8080:8080
    depends_on:
      - db
      - liquibase

volumes:
  db-data:
